### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by Shadowxrp** [duddu/homebridge-shortcuts-buttons#22]
Problem:

Shortcuts buttons not working

I named the shortcuts as instructed with the same name as in shortcuts app . They show up in homekit but nothing happens when I turn them on.

I saw the machine running homebridge must have access to icloud in my case I run homebridge on a raspberry pi. do I have to install icloud on the raspbery pi or is it another plugin in homebridge ? Couldn’t find any instructions on this.. 

Thanks in advance for the help.

**Comment by duddu** [comment]
Hi @Shadowxrp , I'm afraid this plugin requires the host running homebridge to physically have access to the apple Shortcuts application, which as far as I know is only available on macOS. I really don't think there's any way to work around this requirement unfortunately.
Please refer also to the Requirements section of the readme: https://github.com/duddu/homebridge-shortcuts-buttons?tab=readme-ov-file#requirements
