### ISSUE TITLE
Option to make shortcuts stateful

### ISSUE THREAD

**Issue by JonathanGurkan** [duddu/homebridge-shortcuts-buttons#33]
**First off, I just wanted to say thanks a bunch to duddu for creating this incredible plug-in! You really outdid yourself with this one!**

So, while I was checking out the Homebridge library, I came across this plug-in and another one by kylewhirl that had the option to make the accessories stateful. I was really excited about that, but the only catch was that every shortcut you add to the home has to have a separate child bridge, which ended up being a bit too much for my brain to handle.

That’s why I’m writing this feature request. I’d love to see an option added to every shortcut to make it stateful. That way, we can do even more with our shortcuts. For example, I have a fan that can only be controlled via Siri Shortcuts, and I use this plug-in to make a power toggle shortcut that works in Apple Home. But the only problem is that I have to click the button to toggle on and click again to toggle off. I want to have a switch that can display the current state as well, and that’s why I’m making this request.

Thanks for your time and consideration!

Best,
Jonathan Gurkan

**Comment by duddu** [comment]
Hey @JonathanGurkan you make a very interesting point.
Please bear with me, I promise I'll find a moment asap to reflect on your idea and reply to this properly.

**Comment by JonathanGurkan** [comment]
Thanks in advance Davide!

Greetings Jonathan

**Comment by JonathanGurkan** [comment]
@duddu Anything that popped up in your mind?

**Comment by duddu** [comment]
my apologies @JonathanGurkan - had personal issues and this one fell through the cracks.

I got a local branch with a draft boolean state implementation, but it'll take me another few days to fix some errors and push to upstream so you can let me know what you think - time is in short supply.

anyhow, if in the meanwhile you have any draft/code in your fork that you wanna share please feel free of course.

**Comment by JonathanGurkan** [comment]
Dear Davide,

I’m pretty new to plug-in making for Homebridge. In fact, I have little to no experience in plug-in making. I have not forked any Homebridge repositories.
I thought this would be helpful information for you to keep in mind. 

That been said, thank you for your reply. I’m looking forward to the final product! Thanks for actively working in my issue, I really appreciate it. Take any time that you need!

Sincerely yours,
Jonathan Gurkan

**Comment by duddu** [comment]
I'm sorry man, I tried to make this work a couple of times but I ended up with nothing to show. Once I try to introduce the idea of _state_ in the plugin, the ramifications of the consequences always end up messing everything up -- or, more accurately, I'm unable to find any decent way to make the shortcuts buttons optionally stateful without loosing existing functionality/code-flow. 
I'm so sorry, it seemed like a nice challenge, but I'm afraid I'm not able to make it work for the plug-in as it is - it may be possible to achieve if I split the plugin at some point in the future though.
Apologies for the broken promise - I tried!

**Comment by JonathanGurkan** [comment]
It’s not a big dean man. No worries. Maybe in the future this will be easier. I would suggest not closing the issue, but rather put it on maybe. That way we don’t forget about this. All the energy you put into this is very much appreciated
